workflows:
  run-flutter-analyze:
    name: Continuous Integration Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: 3.19.2
      xcode: latest
      cocoapods: default
    scripts:
      - name: Print environment
        script: |
          #!/bin/sh
          set -ex
          printenv
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
          flutter pub global activate intl_utils
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Run build_runner
        script: |
          dart run build_runner build --delete-conflicting-outputs
      - name: Flutter analyze
        script: |
          flutter analyze lib
