workflows:
  run-flutter-analyze:
    name: Continuous Integration Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: 3.19.2
      xcode: latest
      cocoapods: default
    scripts:
      - name: Print environment
        script: |
          #!/bin/sh
          set -ex
          printenv
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze lib
